export const PUSH_TAB_LIST = 'PUSH_TAB_LIST'
export const REMOVE_TAB_LIST = 'REMOVE_TAB_LIST'
export const CLEAR_TAB_LIST = 'FUNNEL_PARAMS'
export const SET_ACTIVE = 'SET_ACTIVE'
export const LISTEN_HASH = 'LISTEN_HASH'
export const HEADER_MENU = 'HEADER_MENU'
